### ISSUE TITLE
Respray Not working on vehicle

### ISSUE THREAD

**Issue by Malfoo** [xXJamieXx/paradox-bugs#179] opened 2022-01-23 15:23 UTC
**Your Discord Name**
Malfo#2515

**Describe the bug**
On the Grotti Brioso R/A Compact car, when I change the respray to another color it does not change. Plate is (PHGD1281) I have seen this car always in this color as way so I don't think it is just me.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy Grotti Brioso
2. Go to Benny's
3. Try respraying

**Expected behavior**
The color of my car is suppose to change

**Screenshots**
https://i.imgur.com/8vQOqvv.jpeg

**Logs**
[Add your FiveM logs]

**Comment by Strandis** [comment] 2022-01-26 09:35
Reported to also happen to Glendale Custom, not sure if intended.

**Comment by Strandis** [comment] 2022-01-26 22:07
Reported to also happen to Vapid Stanier.

**Comment by Person-AL767** [comment] 2022-01-28 06:55
I made a ticket for this a bit ago and I believe Jamie/Jake are closing duplicate tickets and referring to #137 - but yes its happening to a lot of people.

**Comment by xXJamieXx** [comment] 2022-01-28 11:37
Duplicate of #137

**Closed by xXJamieXx** 2022-01-28 11:37 UTC
