### ISSUE TITLE
[BUG] Facial features reverting to default

### ISSUE THREAD

**Issue by gizy559** [xXJamieXx/paradox-bugs#70] opened 2022-01-08 02:49 UTC
**Your Discord Name**
gizy_#1003
**Describe the bug**
when you change clothes after changing your peds skintone/face the skin tone reverts to default

**To Reproduce**
[Steps to reproduce the bug]
1. change peds skin tone/face
2. go to a chothing store and change clothes
3. 

**Expected behavior**
for it to not revert to default

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment] 2022-01-08 16:21
Duplicate of #69

**Closed** 2022-01-08 16:21 UTC
