### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by AssassinJT** [xXJamieXx/paradox-bugs#334] opened 2022-03-26 01:46 UTC
**Your Discord Name**
[James (AssassinJT)]

**Describe the bug**
The trucking depot computer at the south end of the city is completely not interactive. No highlight when using the third eye.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
Be able to interact and start a trucking route

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-26 11:40
duplicate of #335

**Closed by Sly-Panda** 2022-03-26 11:40 UTC
