### ISSUE TITLE
[BUG] Crash when leaving tattoo shop

### ISSUE THREAD

**Issue by BCA-BRIGGS** [xXJamieXx/paradox-bugs#384] opened 2022-04-11 23:10 UTC
**Your Discord Name**
super raccoon#0001

**Describe the bug**
entered the tattoo shop and every time the hit ESC it crashed the game
**To Reproduce**
[Steps to reproduce the bug]
1. enter tattoo shop 
2. buy a tattoo 
3. hit esc 

**Expected behavior**
the game not to crash after you buy tattoos

**Screenshots**

**Logs**

**Comment by Sly-Panda** [comment] 2022-04-23 00:01
Unable to reproduce this, can you provide a log for when this happens so we can look into it.

**Comment by Weebait** [comment] 2022-04-24 21:00
I've had a similar issue it can be avoided by using backspace but every once in a while if you press escape to leave the menu the game freezes on that screen and doesn't let you do anything except restart

**Comment by xXJamieXx** [comment] 2022-07-02 23:36
Fixed by disabling escape in that menu.

**Closed by xXJamieXx** 2022-07-02 23:36 UTC
Labels: Needs Info
