### ISSUE TITLE
[BUG] im stuck in my vehicle stepbro

### ISSUE THREAD

**Issue by ItsFoux** [xXJamieXx/paradox-bugs#299] opened 2022-03-15 18:11 UTC
**Your Discord Name**
Foux#1236

**Describe the bug**
When i pull a sandking out of the garage, it spawns on top of me trapping me inside and no matter what i do i cant get out. had to call Jynx over last night to carry me out from under it with his big strong manly arms 

**To Reproduce**
[Steps to reproduce the bug]
1. buy wicked cool sandking
2. try to pull wicked cool sandking out of parking garage
3. get stuck and have to call stepbro for help

**Expected behavior**
not get stuck inside sandking when pulliing out of garage

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-15 18:55
duplicate of #294

**Closed by Sly-Panda** 2022-03-15 18:55 UTC
