### ISSUE TITLE
[BUG] Crops staying at 1% growth

### ISSUE THREAD

**Issue by Itstoddbruh** [xXJamieXx/paradox-bugs#275] opened 2022-03-11 01:35 UTC
rastapride#3631
[Enter your Discord name]

planted and properly tended to my crops like ive done previous and waited over 20 mins an they were still at 1% growth
[A clear and concise description of what the bug is]

**To Reproduce**
[Steps to reproduce the bug]
1. not sure 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

![image](https://user-images.githubusercontent.com/101373909/157784693-d71b2f7f-0e01-4f12-9a6c-adf5dce448db.png)

![image](https://user-images.githubusercontent.com/101373909/157784716-1c577636-41c5-4d73-877c-53329a6fe076.png)

[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment] 2022-03-11 13:04
I was unable to reproduce this on dev server with multiple plants.

**Comment by xXJamieXx** [comment] 2022-03-26 13:49
This was mostly caused by abuse of the script which has since been fixed. Going to close this for now.

**Closed by xXJamieXx** 2022-03-26 13:49 UTC
Labels: Unable to Reproduce
