### ISSUE TITLE
[BUG] Text sticks to the car

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#219] opened 2022-02-14 19:33 UTC
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[So whenever I fix my car and then put it  back in the garage, the text re-apears on it. I can take it out at Bennys but whenever it goes back to the garage and I pull it out, the text is ther yet again.]

**To Reproduce**
[Steps to reproduce the bug]
1. Re-paint the car / remove livery
2. Park car in garage and take it out
3. No livery on car

**Expected behavior**
[I expected my car to stay the same way as before I parked it when I'd just had the colors done.]

**Screenshots**
[https://i.imgur.com/Lhq5T7C.jpg
![image](https://user-images.githubusercontent.com/98127638/153933515-02b9e9a2-19aa-4c04-8523-e204ad79ff62.png)
]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-12 06:13
duplicate of #30

**Closed by Sly-Panda** 2022-03-12 06:13 UTC
