### ISSUE TITLE
[BUG] Hair clipping through hats

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#153] opened 2022-01-20 02:23 UTC
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[All hair clips through any sort of hats. I have noticed this from the PD side as it has been doing it for a while, Being state its normal for us to wear the hats and my hair is always clipping through the hat.I it depends on the hairstyle but the current one i have shows through alot. I felt like previously the hair shrunk when a hat was placed on the head and now it doesnt do that  ]

**To Reproduce**
[Steps to reproduce the bug]
1. Put on a hat :)
2. 
3. 

**Expected behavior**
[Hat fit good and no hair poking through]

**Screenshots**
[https://i.imgur.com/haP1Xq9.png]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment] 2022-01-20 23:20
Duplicate of #80

**Closed by xXJamieXx** 2022-01-20 23:20 UTC
