### ISSUE TITLE
Fake Storage

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#306] opened 2022-03-18 00:14 UTC
**Your Discord Name**
Cookie#2111

**Describe the bug**
my storage in my car is gone again, I put it in garage 3 times pulled it out still noting, it was full of inventory to farm I just did, and my glove box did the same thing to.

**To Reproduce**
[Steps to reproduce the bug]
1.  Pull Out Car
2.  Look at Inventory of car
3.  See hidden inventory filling up the weight.

**Expected behavior**
Supposed to be at 0 without any item in the glovebox or trunk.

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/98053772/158913772-e324c48a-c4e3-4a24-938d-f8d94c82eb6b.png)
![image](https://user-images.githubusercontent.com/98053772/158913828-dac1050c-76af-4255-b793-251f96a586ce.png)
![image](https://user-images.githubusercontent.com/98053772/158913859-2124314c-7184-4c8b-848d-3cd8321957b1.png)

**Logs**

**Comment by xXJamieXx** [comment] 2022-03-26 15:43
Caused by spamming opening and closing the inventory. Press it once to open it and let it open before hitting it again. Otherwise it causes it visually show like that.

**Closed by xXJamieXx** 2022-03-26 15:43 UTC
