### ISSUE TITLE
[BUG] <RACING APP DOESNT INSTALL ONTO PHONES>

### ISSUE THREAD

**Issue by Tokentys** [xXJamieXx/paradox-bugs#464] opened 2022-05-15 17:15 UTC
### Your Discord Name

Tokentys#7692

### A clear and concise description of what the bug is

When attempting to combine one racing ssd card into a phone, the process doesn’t initiate therefore the card isn’t put into the phone making it impossible to producing racing phones. Normally when using the ssd card it would notify you that the app is installing and after some time the two would be put together into a phone with an ssd installed. 

### Steps to Reproduce the Bug

1. Obtain regular phone.
2. Obtain racing ssd card
3. Use the ssd card with both item in pockets. 
4. notice the items remain in pockets and no notification is given

### Expected Behavior

Normally a notification with a timer bar would appear and then both items would combine and you’d be able to pul the phone out and see a new app on the main screen 

### Screenshots/Videos

N/a

**Comment by xXJamieXx** [comment] 2022-05-15 20:51
Duplicate of #435

**Closed by xXJamieXx** 2022-05-15 20:51 UTC
