### ISSUE TITLE
[BUG] Radar buttons not working

### ISSUE THREAD

**Issue by BigG5904** [xXJamieXx/paradox-bugs#392] opened 2022-04-16 04:18 UTC
**Your Discord Name**
G-Man#0920

**Describe the annoyance**
My PD radar will not open and opening radar and pressing toggle radar. Radar menu also will not close. It stays to my eyes and the only to get to go off is to fly off. I have already changed my phone's keybind to see if this was the problem but it still happens

**To Reproduce**
[Steps to reproduce the annoyance]
1. Press Ctrl+M to open Radar Menu
2. Click on any radar menu icon and nothing happens. Menu won't close.
3. 

**Requested behavior**
To be able to turn on my radar and close the radar so I can catch dirty crimers zooming around the city.

**Screenshots**
https://i.imgur.com/Gc4hni4.jpeg   https://i.imgur.com/DRCtuXh.jpeg   https://i.imgur.com/KfMqaYr.png

**Log Screenshots
https://i.imgur.com/lh4tqKP.png   https://i.imgur.com/3ynKmqK.png   https://i.imgur.com/o4gkBXS.png https://i.imgur.com/3xY1ZqH.png   https://i.imgur.com/o6bsE5a.png   https://i.imgur.com/EPN7RSk.png https://i.imgur.com/iV8TlNF.png   https://i.imgur.com/QcvSAuU.png   https://i.imgur.com/w3FIEz5.png   https://i.imgur.com/qqVsjJo.png   https://i.imgur.com/zqmxs0P.png   https://i.imgur.com/vfg8cr9.png  https://i.imgur.com/clWcvX8.png  https://i.imgur.com/2jol9vk.png  https://i.imgur.com/rmv7dDT.png  https://i.imgur.com/5SGjqAa.png
 
**Additional context**
Video showing what I'm describing. Tried going through MOD support on discord first but they couldn't help with this issue and decided this was a bug. This just recently started happening since last weekend 4/11/22.

https://www.twitch.tv/videos/1457415397

**Comment by xXJamieXx** [comment] 2022-04-16 16:24
Can you actually upload the log file instead of random screenshots in an unknown order? Also this is a bug report not a QOL enhancement...

**Comment by BigG5904** [comment] 2022-04-16 20:54
Here are the logs from 4/9, 4/11, and the first couple from yesterday 4/15 where I tried opening the radar.

[CitizenFX_log_2022-04-09T051403.log](https://github.com/xXJamieXx/paradox-bugs/files/8500628/CitizenFX_log_2022-04-09T051403.log)
[CitizenFX_log_2022-04-11T013740.log](https://github.com/xXJamieXx/paradox-bugs/files/8500629/CitizenFX_log_2022-04-11T013740.log)
[CitizenFX_log_2022-04-16T023639.log](https://github.com/xXJamieXx/paradox-bugs/files/8500630/CitizenFX_log_2022-04-16T023639.log)
[CitizenFX_log_2022-04-16T024556.log](https://github.com/xXJamieXx/paradox-bugs/files/8500631/CitizenFX_log_2022-04-16T024556.log)
[CitizenFX_log_2022-04-16T025454.log](https://github.com/xXJamieXx/paradox-bugs/files/8500632/CitizenFX_log_2022-04-16T025454.log)
[CitizenFX_log_2022-04-16T021654.log](https://github.com/xXJamieXx/paradox-bugs/files/8500633/CitizenFX_log_2022-04-16T021654.log)
[CitizenFX_log_2022-04-16T023015.log](https://github.com/xXJamieXx/paradox-bugs/files/8500634/CitizenFX_log_2022-04-16T023015.log)

**Comment by Sly-Panda** [comment] 2022-04-17 14:01
This is going to be a duplicate of #369 

Temporary solution seems to be switching your FiveM to the **Beta** build (Don't use Canary, it's unstable), that should make it work for you until we get a fix rolled out.

**Closed** 2022-04-23 00:06 UTC
