### ISSUE TITLE
[BUG] Character reset to default look

### ISSUE THREAD

**Issue by TheAzian47** [xXJamieXx/paradox-bugs#192] opened 2022-01-30 00:32 UTC
**Your Discord Name**
TheAzian47#2758
**Describe the bug**
[A clear and concise description of what the bug is]
So I changed my hairstyle and saved it to one of my outfits, then when I went to change into that outfit in my apartment, my character's face returned to the default look
**To Reproduce**
[Steps to reproduce the bug]
1. save a new hairstyle to an outfit
2. change into that outfit in the apartments
3.  pray that your character doesn't revert to default

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment] 2022-03-06 19:09
Duplicate of #117

**Closed by xXJamieXx** 2022-03-06 19:09 UTC
