### ISSUE TITLE
[BUG] Cannot upgrade/spray paint car

### ISSUE THREAD

**Issue by Terrylaughlin35** [xXJamieXx/paradox-bugs#516] opened 2022-06-24 03:09 UTC
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

When I go to upgrade the car or spray paint it i cannot do anything. I cannot click on any of the options given.

### Steps to Reproduce the Bug

1. go to a repair shop with a car
2. hit E to try to upgrade
3. not be able to do anything to your car or any car

### Expected Behavior

be able to spray paint or upgrade my vehicle

### Screenshots/Videos

https://i.imgur.com/iLYYRp8.png
https://i.imgur.com/CdyialT.png

### Log File

[CitizenFX_log_2022-06-24T002232 logs for report.txt](https://github.com/xXJamieXx/paradox-bugs/files/8972891/CitizenFX_log_2022-06-24T002232.logs.for.report.txt)

**Comment by xXJamieXx** [comment] 2022-06-24 19:07
Can't reproduce this. Was able to customize my own vehicle fine. If you could provide more specific reproduction steps it could be something more niche.

**Comment by madsskyy** [comment] 2022-06-24 20:33
I haven’t had this happen to me but i’ve been with 2 different people now who this has happened to and i had to upgrade the cars for them. both happened after buying a car, storing it in a lot, taking it back out then going to upgrade it.

**Comment by Terrylaughlin35** [comment] 2022-06-24 20:53
I cannot use any custom shop for any car. If I steal a car, use a friends car, or my own car I cannot do anything at the custom shop but repair it. it pulls up the options but then will not allow me to click on any of them. this has been a thing for me for a week or so. it isn't an on and off issue for me at least.

**Comment by Terrylaughlin35** [comment] 2022-06-26 00:31
I tried sending a video, but it is too large and i am not smart enough on a computer to shrink it lol

**Comment by Terrylaughlin35** [comment] 2022-06-26 06:53
This also goes for tattoos as well i cannot get any tattoo

**Comment by xXJamieXx** [comment] 2022-07-01 18:34
> I tried sending a video, but it is too large and i am not smart enough on a computer to shrink it lol

If you could upload it to streamable or another video sharing site and copy the link here that would be appreciated.

**Comment by Terrylaughlin35** [comment] 2022-07-03 01:26
https://clips.twitch.tv/CovertFunSandwichImGlitch-TMmrb8wTYcGs16pL

Here is a clip of me trying to do it

**Comment by Sly-Panda** [comment] 2022-07-03 12:15
You say you can't click, have you tried using the arrow keys and enter/backspace to go forward/back?

**Comment by Terrylaughlin35** [comment] 2022-07-03 14:59
I have. I tried those things as well.

**Comment by Terrylaughlin35** [comment] 2022-07-03 15:00
The arrow keys make noises like it's going through options but doesn't show
me them or change anything.

**Comment by xXJamieXx** [comment] 2022-07-03 17:44
Have you changed your keybinds in any way? If so you might want to try resetting them and attempting to use the menu again?

**Comment by Terrylaughlin35** [comment] 2022-07-03 19:32
No I haven't changed why key binds.

**Comment by xXJamieXx** [comment] 2022-07-04 20:18
Fixed by resetting keybinds.

**Closed by xXJamieXx** 2022-07-04 20:18 UTC
Labels: Needs Info, Unable to Reproduce, Waiting for Response
