### ISSUE TITLE
[BUG] Walkthrough walls

### ISSUE THREAD

**Issue by Tobjaks** [xXJamieXx/paradox-bugs#143] opened 2022-01-17 20:45 UTC
**Your Discord Name**
tobjak#4191

**Describe the bug**
The building doesn't have any interior and you can walk through the walls.

**To Reproduce**
[Steps to reproduce the bug]

1. Go up to 1017
2. Enter the "building"

**Expected behavior**
Opened/Closed

**Screenshots**
https://imgur.com/jlQLLO4
https://imgur.com/FwKpzAW
https://imgur.com/0GmALcd

**Comment by xXJamieXx** [comment] 2022-01-18 20:21
Duplicate of #1

**Closed by xXJamieXx** 2022-01-18 20:21 UTC
