### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#185] opened 2022-01-26 18:29 UTC
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[Still gets Dannyface and different haircolor. Makeup is green, eyebrows too.]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[Expected to wake up like yesterday. Look like a Danny with green brows and blush. Can change face without issue, but not makeup or brows.]

**Screenshots**
(https://i.imgur.com/Gzmrjh7.jpg)

**Comment by xXJamieXx** [comment] 2022-03-06 19:08
Duplicate of #117

**Closed by xXJamieXx** 2022-03-06 19:08 UTC
