### ISSUE TITLE
Danny face mites in the apartment closets 

### ISSUE THREAD

**Issue by TeddyNM** [xXJamieXx/paradox-bugs#228] opened 2022-02-19 04:06 UTC
**Your Discord Name**
[TeddyMercury#4685]

**Describe the bug**
[After changing my outfit a couple of times at the closet in my apartment I'm changed to Danny face. This has happened before but just figured out it is when you change your outfit several different times]

**To Reproduce**
[Steps to reproduce the bug]
1. Change outfit at the closet in the apartment 
2. Repeat step 1 
3. Danny face

**Expected behavior**
[I expected to be able to flip through my outfits and decide which one I wanted and not have to go get reconstructive surgery]

**Screenshots**
[
![image](https://user-images.githubusercontent.com/97271676/154785129-2424e60b-8d3e-41ea-a434-63f7e5497038.png)

]

**Logs**
[
![20220218195354_1](https://user-images.githubusercontent.com/97271676/154785474-ce8a3e39-93c2-49d8-86ca-d46c8d10881d.jpg)]

**Comment by xXJamieXx** [comment] 2022-03-06 19:09
Duplicate of #117

**Closed by xXJamieXx** 2022-03-06 19:09 UTC
