### ISSUE TITLE
[BUG] PCJ-600 Wont be painted

### ISSUE THREAD

**Issue by Kevbot44** [xXJamieXx/paradox-bugs#131] opened 2022-01-16 11:45 UTC
**Your Discord Name**
King Raccoons#1781

**Describe the bug**
I bought the PCJ-600 and colored it before buying. i went to put it up, got it out, went to bennys to color it and couldnt

**To Reproduce**
[Steps to reproduce the bug]
1. Buy the PCJ-600 and color it before buying
2. Put it in the garage and take it out
3. Go to bennys and try to paint it

**Expected behavior**
To change the primary and secondary colors

**Screenshots**
[If applicable, add screenshots to help explain your problem]
https://medal.tv/games/undefined/clips/7YJPI0P7t7jbC/zvfOh2JMqzlE

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment] 2022-01-18 19:49
Duplicate of #130

**Closed by xXJamieXx** 2022-01-18 19:49 UTC
