### ISSUE TITLE
[BUG] Not being able to respray certain vehicles 

### ISSUE THREAD

**Issue by Sockrockr** [xXJamieXx/paradox-bugs#175] opened 2022-01-22 01:43 UTC
**Your Discord Name**
[Sock Rocker]

**Describe the bug**
There are certain vehicles in the city that you cannot respray at any mechanic shop or bennys

**To Reproduce**
[Steps to reproduce the bug]
1.Grab any vehicle (some work, some don't) 
2.Pull into any mechanic shop or bennnys  
3.And try to respray the vehicle 

**Expected behavior**
The color of my vehicle to change

**Screenshots**
https://i.imgur.com/2dNW2EC.jpeg
https://i.imgur.com/NIscG54.jpeg (Color doesn't change)
**Additional context**
I think only for the low-end vehicles or local cars perhaps this happens but don't quote me on that.
(Thank you for your time, Love the server!)

**Comment by xXJamieXx** [comment] 2022-01-22 15:29
Duplicate of #137

**Closed by xXJamieXx** 2022-01-22 15:29 UTC
