### ISSUE TITLE
[BUG] Armor disappearance 

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#550] opened 2022-07-09 03:58 UTC
### Your Discord Name

PadawanPepsi#6898

### A clear and concise description of what the bug is

I had a vest on from PD armory and I took one shot to it maybe 2 CM were missing on the armor icon. When I was about to get off duty I noticed the armor icon was gone. I tried to /removearmor and it said I had no vest on I also tried /removevest.      I tried this the other day when I took no damage to armor again the icon disappeared and later when I tried to do the command nothing happened. 

### Steps to Reproduce the Bug

Put on a armor and see if it stays on

### Expected Behavior

The armor should stay on and i believe it should even stay on if you nap but it seems to disappear even if you take no damage

### Screenshots/Videos

i have none

### Log File

[CitizenFX_log_2022-07-09T000258.log](https://github.com/xXJamieXx/paradox-bugs/files/9075839/CitizenFX_log_2022-07-09T000258.log)

**Comment by xXJamieXx** [comment] 2022-07-09 19:32
Can't reproduce this. Is there any other steps I should be following to reproduce this 100% of the time?

**Comment by PadawanPepsi** [comment] 2022-07-09 21:10
i wear an actuall vest clothing item and for RP i often do /v0 and /v1 to take it on and off maybe thats messing with it?

**Comment by PadawanPepsi** [comment] 2022-07-10 19:42
i was told changing your cloths will delete the armor

**Comment by Sly-Panda** [comment] 2022-07-10 20:44
Yup looks like changing clothes was deleting the armor short term (until a relog or some other thing triggers it to return)  v0 and v1 should have no effect on it.

Should be fixed next update

**Closed** 2022-07-11 15:33 UTC
Labels: Unable to Reproduce, Waiting for Response
