### ISSUE TITLE
[BUG] Cannot refuel boats

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#396] opened 2022-04-16 19:18 UTC
**Your Discord Name**
[CYBERCUCKED 2077#9166]

**Describe the bug**
[When going using my third eye on my boat the option to refuel does not show up, i thought it was because i needed to fill up my gas can but that did not change anything, all other third eye options show up on the boat, its only the refuel option that's now missing.]

**To Reproduce**
[Steps to reproduce the bug]
1. Take out boat from docks
2. Use Third eye on boat
3. All other third eye suggestions pop up except for refuel

**Expected behavior**
[I expected to be able to refuel my boat]

**Screenshots**
![Screenshot (176)](https://user-images.githubusercontent.com/99993392/163688471-1c8199f5-28d3-4d4c-acaa-b213c8e16580.png)
[]

**Logs**
[
[CitizenFX_log_2022-04-16T190712.log](https://github.com/xXJamieXx/paradox-bugs/files/8500518/CitizenFX_log_2022-04-16T190712.log)
]

**Comment by xXJamieXx** [comment] 2022-04-17 00:13
Duplicate of #391

**Closed by xXJamieXx** 2022-04-17 00:13 UTC
