### ISSUE TITLE
[BUG] changing into civilian clothing via PD locker

### ISSUE THREAD

**Issue by LittletonSniper** [xXJamieXx/paradox-bugs#34] opened 2022-01-02 22:25 UTC
LittletonSniper

**Describe the bug**
When you change into a personal outfit via the PD locker, it put's your character as a danny with green hair.
This doesn't happen every time, but it has happened a few times, like today for example 

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
I expected it to just change me into my outfit and not make me pale white with green hair

**Screenshots**
https://i.imgur.com/oqkI18l.png

**Additional context**
F8 Error
https://i.imgur.com/RFZQIHx.png

**Comment by JnKTechstuff** [comment] 2022-01-03 11:57
Duplicate of: https://github.com/xXJamieXx/paradox-bugs/issues/35

**Closed by JnKTechstuff** 2022-01-03 11:57 UTC
