### ISSUE TITLE
[BUG] GSR Testing

### ISSUE THREAD

**Issue by StealthyRiot** [xXJamieXx/paradox-bugs#178] opened 2022-01-22 18:57 UTC
**Your Discord Name**
Stealthy_Riot#9382

**Describe the bug**
I am not sure if this is a bug or QOL issue but we are able to unload 10 shots with our weapons and still get a negative GSR Result. 4 of us officers went to the firing range after multiple shots fired calls where we were confident we caught the suspect, but then could not get enough probable cause to search them due to the negative GSR Tests. It appears that maybe if you unload a complete clip at once, it will come back positive. Taking a few short bursts overtime, comes back negative. 

**To Reproduce**
[Steps to reproduce the bug]
1. Fire 3-5 shots with your pistol
2. GSR the person that shot
3. 

**Expected behavior**
If a person has fired enough shots to down someone, I feel that they should come back GSR positive

**Screenshots**
https://www.twitch.tv/videos/1272427039
https://www.twitch.tv/videos/1272427040

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-04-17 12:22
Is this still an issue?  Seems to be working as intended from my tests.

**Comment by StealthyRiot** [comment] 2022-04-17 15:12
This is still an issue, just tested yesterday with a cadet: https://www.twitch.tv/videos/1458743138

**Comment by Sly-Panda** [comment] 2022-04-17 15:32
Without going into specifics you won't always get a positive result from every gunshot, can you try again emptying a full clip and feedback the results of that when you get a sec?

**Comment by Sly-Panda** [comment] 2022-04-17 18:37
Should be fixed next update.

**Closed by Sly-Panda** 2022-04-17 18:37 UTC
