### ISSUE TITLE
[BUG] Business Paychecks not being paid since morning tsunami

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#298] opened 2022-03-15 17:48 UTC
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
No paychecks from businesses since morning restart - can see in logs none received at any business. 

**To Reproduce**
[Steps to reproduce the bug]
1.  Don't get paid
2. 
3. 

**Expected behavior**
To be paid

**Screenshots**

**Logs**
check #business-logs

**Comment by xXJamieXx** [comment] 2022-03-15 17:54
Duplicate of #272

**Closed by xXJamieXx** 2022-03-15 17:54 UTC
