### ISSUE TITLE
[BUG] Gun Quality

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#160] opened 2022-01-20 10:42 UTC
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[The quality of our firearms cant last passed one shootout. They break super easily ]

**To Reproduce**
[Steps to reproduce the bug]
1. Buy a gun
2. Shoot it
3. it breaks

**Expected behavior**
[Personally i expect to be able to use a firearm longer than one shootout. before the attached clip i go down to locals due to my gun breaking mid shootout. Attached video is me shooting 2 or 3 clips and the durability goes down over half. a total of 24 bullets shot. ]

**Screenshots**
[Before screenshot https://i.imgur.com/ym9rtVH.png    After screenshot https://i.imgur.com/sPP3kgN.png ]

**Additional context**
[https://medal.tv/games/requested/clips/8mK7wILLyVELR/d1337sVpxYVH?invite=cr-MSxOSm8sNDQ0ODc0NTAs]

**Comment by xXJamieXx** [comment] 2022-01-20 23:18
Duplicate of #118

**Closed by xXJamieXx** 2022-01-20 23:18 UTC
