### ISSUE TITLE
[BUG] Fingerprints arent updated to MDT and makes it hard to search individuals.

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#206] opened 2022-02-04 22:57 UTC
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
After using fingerprint to identify someone, The search of the fingerprint ID shows no results. Once identified by a reprint of the persons ID at town hall, Civilian comes up in MDT with Fingerprint : Undefined

**To Reproduce**
[Steps to reproduce the bug]
1. Find someone who's fingerprint is undefined
2.  search their fingerprint
3. yields no results.

**Expected behavior**
If searching by fingerprint, it should pop up with their identity for easier identifications and to work properly or to allow us the ability to change the fingerprint and add it to the profile.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-06 22:00
Duplicate of #89

**Closed by Sly-Panda** 2022-03-06 22:00 UTC
Labels: Duplicate
