### ISSUE TITLE
[BUG] Garbageman Job not allowing me to pickup trashbags

### ISSUE THREAD

**Issue by AnarchyDemon** [xXJamieXx/paradox-bugs#33] opened 2022-01-02 20:43 UTC
**Your Discord Name**
Psycho#0537

**Describe the bug**
I started up the garbageman job, and on the second location (363 on map) none of the trash cans or dumpsters would let me pick up trash bags from them. The first location worked fine, but the second one isn't working

**To Reproduce**
I don't know how to reproduce, all i did was start the garbage depot job, and finish the first location.
**Expected behavior**
I expected to arrive to the second location and pick up trash bags to put into the garbage truck

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment] 2022-01-02 23:30
@AnarchyDemon I can't find a garbage location at 636. I screenshot of the map and location in the world might help track down the issue.

**Comment by AnarchyDemon** [comment] 2022-01-03 12:43
edit: mistyped 363 as 636

**Comment by xXJamieXx** [comment] 2022-01-03 13:38
Duplicate of #15

**Closed by xXJamieXx** 2022-01-03 13:38 UTC
Labels: Duplicate
