### ISSUE TITLE
[BUG] Lost all of my car modifications completely and now have to pay to get them back 

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#225] opened 2022-02-18 19:49 UTC
**Your Discord Name**
[CYBERCUCKED 2077 /TurboDummi]

**Describe the bug**
[When i brought my car to get repaired i lost all of my modifications and have to pay for them all over again]

**To Reproduce**
[Steps to reproduce the bug]
1. went into a los santos customs
2. repaired my truck
3. lost all my mods completely and now i have to pay 7 grand to get them back again (offroading tires, rockcrawler wheels, level 3 ems tune, level 2 brakes, and xeon lights all wiped clean off my contender)

**Expected behavior**
[I expected my car to be repaired as normal]

**Screenshots**

![Screenshot (54)](https://user-images.githubusercontent.com/99993392/154748613-e7d603f4-9490-47e7-b061-0daf468a7b80.png)
  
![Screenshot (53)](https://user-images.githubusercontent.com/99993392/154748676-13c6bf74-9ef8-49e7-9b85-1eb5e5df8282.png)
 
![Screenshot (52)](https://user-images.githubusercontent.com/99993392/154748715-38000472-9624-44fc-a235-d2dadfd5d9cb.png)

![Screenshot (51)](https://user-images.githubusercontent.com/99993392/154751062-c0484f43-301b-40ae-9060-3e51ee95cdc0.png)

![Screenshot (50)](https://user-images.githubusercontent.com/99993392/154751151-730d35a3-5480-4b32-88f2-b93f8f15607d.png)

![Screenshot (49)](https://user-images.githubusercontent.com/99993392/154751164-a429f09b-0470-48e4-b98b-38880e8bac3a.png)

**Logs**
[Add your FiveM logs]

**Comment by TurboDummi** [comment] 2022-02-18 20:12
also forgot to mention my other modification lost was fuel octane level 2.

**Comment by Sly-Panda** [comment] 2022-03-12 06:03
duplicate of #212

**Closed by Sly-Panda** 2022-03-12 06:03 UTC
