### ISSUE TITLE
I have a slushy that works forever

### ISSUE THREAD

**Issue by Flawlessdx** [xXJamieXx/paradox-bugs#351] opened 2022-03-28 22:17 UTC
**Your Discord Name**
Flawless#8302

**Describe the bug**
When i first when in to the city today i took out just one slushy and i saw that i could use the one over and over agien and still have it in my pockets, still have it in my pocket.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment] 2022-03-31 15:40
Duplicate of #350

**Closed by xXJamieXx** 2022-03-31 15:40 UTC
