### ISSUE TITLE
[BUG] Faction does not repaint

### ISSUE THREAD

**Issue by ImPaulYo** [xXJamieXx/paradox-bugs#177] opened 2022-01-22 15:51 UTC
**Your Discord Name**
Carbon#7678

**Describe the bug**
My Willard Faction cant respray. Ive bought other resprays and nothing happens. Now I just check for the preview to see if i can paint it

**To Reproduce**
[Steps to reproduce the bug]
1. Drive faction to Bennys
2. Go to respray
3. does not respray

**Expected behavior**
To see the preview of colors

**Screenshots**
![image](https://user-images.githubusercontent.com/98225538/150645691-03ee01cc-0cc9-46a2-adc2-f6766c4fadbf.png)

**Additional context**
i have confirmed before that when you purchase a paint, nothing happens and you are charged

**Comment by JnKTechstuff** [comment] 2022-01-22 16:18
Duplicate of: https://github.com/xXJamieXx/paradox-bugs/issues/137

**Closed by JnKTechstuff** 2022-01-22 16:18 UTC
