### ISSUE TITLE
[BUG] PD Body Armor

### ISSUE THREAD

**Issue by 211Walker** [xXJamieXx/paradox-bugs#409] opened 2022-04-20 00:30 UTC
**Your Discord Name**
tonytone883

**Describe the bug**
I was in a shootout where I was wearing body armor.  The body armor was completely used. When I loaded back into the city my armor is back to full.  I'm sure this should not be happening. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96933759/164122518-416dc0e6-60da-47ff-9e00-7d616e49cad8.png)

**Comment by JnKTechstuff** [comment] 2022-04-20 09:56
Can happen randomly, but should not be considered a huge issue

**Comment by Sly-Panda** [comment] 2022-04-28 03:35
duplicate of #383  (which has a lot more info)

**Closed by Sly-Panda** 2022-04-28 03:35 UTC
