### ISSUE TITLE
[BUG] Alt key is escorting criminals 

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#72] opened 2022-01-08 16:07 UTC
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[While escorting a suspect to The PD flexing ALT to turn on the siren it grabbed the person from the back seat and i was not escorting them. also happened while trying to fine and jail the suspect i was continually grabbing them through the cell over and over. solution was to walk away open third eye then walk up to them and process as normal  ]

**To Reproduce**
[Steps to reproduce the bug]
1. Should just press ALT and they should be escorted 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Seems to only happen to certain people trying to press ALT happened to myself and one other officer but not gabafool]

**Comment by xXJamieXx** [comment] 2022-01-08 18:04
@JaxCreed Cannot reproduce this issue myself, could you attach a video of the bug so we can see it happening. Please also open your F8 during the video after reproducing the bug.

**Comment by Tobjaks** [comment] 2022-01-17 07:43
I can vouch for this happening a lot during EMS as well. Only thing that works is to /escort to let them go, we call it sticky fingers. As soon as you try to look back at them with the third eye it hooks them back on you. 

Sometimes it works with someone taking them off of you, sometimes you just gotta work around it, like getting them checked in etc. 

It usually works with the next patient like normal. If needed, I can get a clip of this next time it happens.

**Comment by jibbersh** [comment] 2022-03-06 17:54
This bug is still happening, would need some better testing to understand the conditions with which it happens, I will try to get some testing done soon on this to help add info. (has not happened to me, heard it happened to an EMS last night)

**Comment by Sly-Panda** [comment] 2022-03-12 06:10
I believe this is caused by a conflicting keybind.  If you go to Keybinds > General and change Character Selector to something other than left alt it should fix it. 

If anyone having this issue is able to try this, please do and post an update here.

**Comment by xXJamieXx** [comment] 2022-04-14 11:09
Due to lack of response, going to assume this resolved the issue.

**Closed by xXJamieXx** 2022-04-14 11:09 UTC
Labels: Needs Info
