### ISSUE TITLE
[BUG] Locked Truck can Still be accessed

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#145] opened 2022-01-18 01:24 UTC
**Your Discord Name**
BDZ#0001

**Describe the bug**

After locking your car, you are still able to take things out of the car/truck. Tried restarting the game and it still is bugged.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by supawiz6991** [comment] 2022-01-18 16:42
I've seen this as well. Me and a friend had rocks in the back of his truck, he locked the truck and someone was still able to steal them in just the couple of minutes we were inside the refinery.

**Comment by xXJamieXx** [comment] 2022-01-18 19:21
Duplicate of #142

**Closed by xXJamieXx** 2022-01-18 19:21 UTC
