### ISSUE TITLE
walk through wall at 3025

### ISSUE THREAD

**Issue by ItsFoux** [xXJamieXx/paradox-bugs#277] opened 2022-03-11 04:34 UTC
**Your Discord Name**
Foux#1236

**Describe the bug**
at the convenience store atm at 3025 next to the picnic tables, you can just walk right through the wall to the right.

**To Reproduce**
[Steps to reproduce the bug]
1. got to atm for money
2. go to the right
3. immersion broke

**Expected behavior**
not have superpowers

**Screenshots**
![inside wall](https://user-images.githubusercontent.com/101135963/157802659-3cf9d98b-ff2b-4fc0-91d6-2be2958fac98.jpg)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-12 05:46
duplicate of #266

**Closed** 2022-03-12 05:46 UTC
