### ISSUE TITLE
[BUG] Reset car tuning

### ISSUE THREAD

**Issue by AiZeNwashere** [xXJamieXx/paradox-bugs#221] opened 2022-02-17 14:41 UTC
Your Discord Name
AiZeN#7220

Describe the bug
My tuning for my Declasse Vamos reseted after i parked it at The Hotel Parking. I parked it there cause i wanted to use the atm next to the clothing store and when i took it back out and all tuning was gone. I drove back to Marathon Ave and parked it there and took it out again to see what would happen but the upgrades and cosmetics were still reseted. I also deleted the Fivem cache to see if that would change anything but it didnt.  The only thing that stayed was my black mat respray and the dark window tint. *Edit:* i meant the hotel parking not motel sorry i got confused

To Reproduce
[Steps to reproduce the bug]

1. Upgrade car (in my case it was EMS, Suspension Coilover upgrade 4 ,Brake Pad upgrade 3 and Fuel Octane upgrade 2 as well as various cosmetics.)
2. store it in the hotel parking
3. take it back out

Expected behavior
I expected to see my car with all upgrades and cosmetics i bought for it.

Screenshots
I had no screenshots or clips because I was driving to pick up some friends and didnt expect it to happen.

Logs
[CitizenFX_log_2022-02-17T075811.log]
(https://github.com/xXJamieXx/paradox-bugs/files/8089475/CitizenFX_log_2022-02-17T075811.log)

**Comment by Sly-Panda** [comment] 2022-03-12 06:11
duplicate of #212

**Closed by Sly-Panda** 2022-03-12 06:11 UTC
