### ISSUE TITLE
[BUG] Waking up as a Danny

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#204] opened 2022-02-04 00:09 UTC
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[Whenever I change clothes, turns in to Danny. Log back in after storm? Danny.]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[To wake up/Change clothes without being a Danny]

**Screenshots**
(https://user-images.githubusercontent.com/98127638/152450139-10a3da92-4ae8-4dbc-893b-09e9b7e6b831.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment] 2022-03-06 19:09
Duplicate of #117

**Closed by xXJamieXx** 2022-03-06 19:09 UTC
