### ISSUE TITLE
[BUG] 1 Weight in Glovebox when empty

### ISSUE THREAD

**Issue by drl0934** [xXJamieXx/paradox-bugs#271] opened 2022-03-09 21:06 UTC
**Your Discord Name**
l Pcakes l / Logan Crowe

**Describe the bug**
When checking my truck glovebox it show 1 weight when nothing is in the glovebox

**To Reproduce**
[Steps to reproduce the bug]
1. Open Glovebox
2. 
3. 

**Expected behavior**
There should be a 0 weight when nothing is in there

**Screenshots**
![Glovebox](https://user-images.githubusercontent.com/64165395/157535913-fdfff8ad-6150-431b-9103-d5aa74194336.png)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-12 06:12
Can't reproduce this, needs more info.

**Comment by drl0934** [comment] 2022-03-12 06:50
No matter if I park it and take it out or put something in the truck the and take it out the truck shows 1 weight when its empty

**Comment by jibbersh** [comment] 2022-03-12 07:04
Please provide more info.
When this started happening, if it always happens, what type of car, if it happens in other cars, any messages that pop up in F8 when you pull it out of a garage or access the glovebox, etc.

Attempted to reproduce this on multiple different cars in different states, was unable to.

**Comment by drl0934** [comment] 2022-03-12 10:33
Im not sure when it started I noticed it the day I put the bug report in the car is a Bravado Bison and it doesnt happen with any other cars just that one and nothing comes up in the f8 menu that I can see

**Comment by SterlingMoss** [comment] 2022-03-28 19:32
This has been happening to me for about 3 months, jake tried to help and found out it was a dremmel bit in my instance, but couldnt figure out how to fix it. this is an issue with at least a few of my cars

**Comment by xXJamieXx** [comment] 2022-06-13 22:53
Pushed a possible fix for this issue. Updates would be great if possible. The items adding to the weight are in slots that shouldn't be possible with a glovebox given it has 5 max and so the script will now attempt to move the item to the first available slot. Let me know how this goes :)

**Comment by xXJamieXx** [comment] 2022-06-18 19:53
Applied a bandaid fix for this which should resolve invisible items.

**Closed** 2022-06-19 21:31 UTC
Labels: Confirmed
