### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by LtNathan235** [xXJamieXx/paradox-bugs#423] opened 2022-04-26 01:56 UTC
**Your Discord Name**
Lnathan#2957

**Describe the bug**
baseball bats do not work, after purchasing a bat, you cannot pull it out of you pockets and hold it, no features do not work with it.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy a bat
2. Pull it out...
3. Watch it not work

**Expected behavior**
To be able to pull out the bat and swing it/hit people

**Screenshots**
none

**Logs**
none

**Comment by Sly-Panda** [comment] 2022-04-27 23:07
duplicate of #265

**Closed by Sly-Panda** 2022-04-27 23:07 UTC
