### ISSUE TITLE
[BUG] gas tank reset after changing garage

### ISSUE THREAD

**Issue by xXvolcanoXx** [xXJamieXx/paradox-bugs#404] opened 2022-04-19 15:54 UTC
**Your Discord Name**
volcano#3927

**Describe the bug**
so if u park ur car in any garage and then take it out and park it in another garage it will reset the gas tank 

**To Reproduce**

1. park in legion
2. get ur car out and refuel it
3. park it again in another garage
4. take it out 
5. gg u just lost a 100$

**Expected behavior**
to not rest the gas to the way it was when i took it out 

**Screenshots**
https://medal.tv/games/gta-v/clips/ilaq1Vii25uWV/d13374QWg9f8?invite=cr-MSw2dFMsNjE3NzM1NzYs

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment] 2022-04-22 12:44
Duplicate of #393

**Closed by xXJamieXx** 2022-04-22 12:44 UTC
