### ISSUE TITLE
Third eye doesnt turn purple when looking at trucking laptop

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#338] opened 2022-03-26 20:52 UTC
**Your Discord Name**
[CYBERCUCKED 2077/ TURBO DUMMI]

**Describe the bug**
Used my third eye at the depot and it wouldn't change to purple when looking at laptop or near it]

**To Reproduce**
[Steps to reproduce the bug]
1. Go to trucking
2. use third eye on laptop
3. third eye stays white

**Expected behavior**
[Expected third eye to turn purple and I would be able to do trucking as usual]

**Screenshots**
![Screenshot (129)](https://user-images.githubusercontent.com/99993392/160256662-6dfd8a43-d716-4849-9251-ae46cc279786.png)

**Logs**
nothing

**Comment by xXJamieXx** [comment] 2022-03-26 20:53
Duplicate of #335

**Closed by xXJamieXx** 2022-03-26 20:53 UTC
