### ISSUE TITLE
[BUG] Space in glovebox

### ISSUE THREAD

**Issue by Mac-ceo** [xXJamieXx/paradox-bugs#506] opened 2022-06-18 18:54 UTC
### Your Discord Name

mac_ceo#7021

### A clear and concise description of what the bug is

The glovebox or trunk of some vehicle will have invisible items which cant be grabbed but will show as weight in the storage

### Steps to Reproduce the Bug

I am not sure on how to repoduce

### Expected Behavior

What's meant to happen is when an item is removed the weight should be as well 

### Screenshots/Videos

![20220618192000_1](https://user-images.githubusercontent.com/103427821/174452204-869a2595-8059-41ae-a59d-311baea1e258.jpg)

### Extra Notes (Optional)

Plate: PMME4888
Vehicle: Hellion
item  [15] 1x Plant Fertilizer (plant_nutrition)

### Log File

[CitizenFX_log_2022-06-18T164410.log](https://github.com/xXJamieXx/paradox-bugs/files/8934135/CitizenFX_log_2022-06-18T164410.log)

**Comment by xXJamieXx** [comment] 2022-06-18 19:53
Duplicate of #271

**Closed by xXJamieXx** 2022-06-18 19:53 UTC
