### ISSUE TITLE
[BUG] Can't Place Scenes on Building Walls

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#542] opened 2022-07-02 16:43 UTC
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When placing a scene, a scene can be placed on an object or the floor outside a building, but not on the building itself.

### Steps to Reproduce the Bug

1. K key to make a scene
2. Make a Scene with some letters
3. Try to place it on a wall.

### Expected Behavior

That the writing would be on the wall, or where you place it.

### Screenshots/Videos

![PlaceScene](https://user-images.githubusercontent.com/98053772/177009089-941ddbff-8aa4-4691-a5e1-1b9f12f5bab2.PNG)
![EndResultScene](https://user-images.githubusercontent.com/98053772/177009092-6d514224-b90c-4790-812a-f07e54fa0b3a.PNG)

### Log File

[SceneTest.txt](https://github.com/xXJamieXx/paradox-bugs/files/9033330/SceneTest.txt)

**Comment by Sly-Panda** [comment] 2022-07-02 23:42
duplicate of #538

**Closed by Sly-Panda** 2022-07-02 23:42 UTC
