### ISSUE TITLE
[BUG] Car boosting

### ISSUE THREAD

**Issue by LittletonSniper** [xXJamieXx/paradox-bugs#42] opened 2022-01-03 05:41 UTC
LittletonSniper

**Describe the bug**
When someone does the new car boosting script the GPS that updates is always on him not matter what vehicle he switches into. We arrested the guy who had the gps disabler, so he wasn't able to disable the gps for the vehicle. So the driver switched vehicles but he continued to have that gps on him.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
the GPS be synced to the car not the individual

**Screenshots**

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment] 2022-01-03 12:16
Duplicate of https://github.com/xXJamieXx/paradox-bugs/issues/43

**Closed by JnKTechstuff** 2022-01-03 12:16 UTC
Labels: Duplicate
