### ISSUE TITLE
[BUG] <REPLACE ME WITH YOUR BUG TITLE>

### ISSUE THREAD

**Issue by jkaejkae888** [xXJamieXx/paradox-bugs#482] opened 2022-05-31 21:10 UTC
### Your Discord Name

jkaejkae888

### A clear and concise description of what the bug is

Every time there is a house alarm in the hills, multiple Officers will head pop and not be able to fly back into their last location. I" have only heard of it happening in the hills. update on logs

### Steps to Reproduce the Bug

Has happened multiple times over the past few weeks.

### Expected Behavior

Be able to respond to house robbery calls.

### Screenshots/Videos

n/a

### Extra Notes (Optional)

just an extra log update for you guys

### Log File

[CitizenFX_log_2022-05-31T195532.log](https://github.com/xXJamieXx/paradox-bugs/files/8809449/CitizenFX_log_2022-05-31T195532.log)

**Comment by Sly-Panda** [comment] 2022-05-31 21:20
duplicate of #479

**Closed by Sly-Panda** 2022-05-31 21:20 UTC
