### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by Blake342** [xXJamieXx/paradox-bugs#432] opened 2022-04-28 00:42 UTC
**Your Discord Name**
[Blake.#1655

**Describe the bug**
[Duplication glitch]

**To Reproduce**
[Steps to reproduce the bug]
1. give a item to a friend 
2. they  have full inv
3. its on the ground and still in your inv 

**Expected behavior**
[it to go away people could abuse this with like guns ]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-04-28 00:51
duplicate of #422

**Closed by Sly-Panda** 2022-04-28 00:51 UTC
