### ISSUE TITLE
[BUG] Cannot Third Eye Benches 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#329] opened 2022-03-25 05:37 UTC
**Your Discord Name**
[Enter your Discord name]
Vsolon#1699
**Describe the bug**
[A clear and concise description of what the bug is]
Cannot seem to use third eye on the crafting benches. I have tried flying in and out, and clearing my cache but that has not change anything. They're also just pure black for me, I have attempted to use several of the benches and they're all like this. This also seems to be the case for several others. 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to a bench 
2. Try to third eye it 

**Expected behavior**
[A clear and concise description of what you expected to happen]
You should be able to third eye the bench 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/13530791/160060919-28c813a3-228c-4e8c-b1a5-ea167bba45a8.png)
https://i.imgur.com/4abx7Om.mp4
**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-25 06:35
The visuals will be your graphics, as for the third eye I'm able to third eye the benches fine.  Try third eye the closest part of the bench to your character and let me know if it's working.

**Comment by Sly-Panda** [comment] 2022-03-25 07:06
Did a little more digging and it managed to reproduce this, a server restart should hopefully sort it.

**Comment by Sly-Panda** [comment] 2022-03-25 11:16
Have tested this on live since restart and seems to be working now.

**Comment by Sly-Panda** [comment] 2022-03-25 16:31
Awesome, I'll go ahead and close this.

**Closed by Sly-Panda** 2022-03-25 16:31 UTC
Labels: Confirmed
