### ISSUE TITLE
[BUG] Can't farm

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#343] opened 2022-03-27 08:05 UTC
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[Whenever I try to water/fertilize my plants it just says Action impossible.]

**To Reproduce**
[Steps to reproduce the bug]
1. Plant something
2. Try to give it water
3. 

**Expected behavior**
[To be able to give my crops water and fertilizer ]

**Screenshots**
(https://medal.tv/games/gta-v/clips/fHfXeo_CSEhrS/d1337y6vIv7o?invite=cr-MSw3UEIsNDU3NjU0MzAs)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment] 2022-03-27 12:54
Duplicate of #341

**Closed by xXJamieXx** 2022-03-27 12:54 UTC
