### ISSUE TITLE
Blueprint not showing up when doing garbage

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#346] opened 2022-03-27 22:17 UTC
**Your Discord Name**
[Cybercucked 2077/ turbo dummi]

**Describe the bug**
[Went to do some garbage runs and was told that I found a blueprint in the trash but when I checked my wallet nothing was there]

**To Reproduce**
[Steps to reproduce the bug]
1. go do trash pickup
2. pickup trash
3. get notified I found a blueprint but nothing shows up

**Expected behavior**
[I expected to receive a blueprint]

**Screenshots**
None I was too slow to screenshot the notification :(

**Logs**
[Nothing when I checked logs]

**Comment by Sly-Panda** [comment] 2022-03-27 22:22
duplicate of #301

**Closed by Sly-Panda** 2022-03-27 22:22 UTC
