### ISSUE TITLE
[BUG] Diving locations not showing

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#411] opened 2022-04-20 21:23 UTC
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
No diving locations on the map

**To Reproduce**
1. Open your map
2. See no yellow circles for diving
3. 

**Expected behavior**
Find diving locations when I open my map

**Screenshots**
![20220420222315_1](https://user-images.githubusercontent.com/96963965/164325305-4a386aaf-ee96-48ea-abdd-690929f78987.jpg)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-04-22 23:03
Duplicate of #407

**Closed by Sly-Panda** 2022-04-22 23:03 UTC
