### ISSUE TITLE
[BUG] Hair clipping through masks

### ISSUE THREAD

**Issue by Gesundhype** [xXJamieXx/paradox-bugs#200] opened 2022-01-31 03:18 UTC
**Your Discord Name**
Gesundhype#6485

**Describe the bug**
Any hair that is not slicked down will clip through helmets in the mask selection

**To Reproduce**
[Steps to reproduce the bug]
1. Have non slicked hair (ex. hair 10)
2. put on mask 
3. observe that hair pokes through

**Expected behavior**
Hair should not appear above mask

**Screenshots**
![hair](https://user-images.githubusercontent.com/98724542/151734350-c76c4c27-bc77-4ed8-aab3-c5d2e013d9be.PNG)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment] 2022-03-12 06:17
duplicate of #80

**Closed by Sly-Panda** 2022-03-12 06:17 UTC
